### ISSUE TITLE
whan i add a utf8 chars

### ISSUE THREAD

**Issue by texrg** [jekyll/classifier-reborn#175]
/home/oo/.gem/ruby/gems/classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:313:in `sort': comparison of Float with NaN failed (ArgumentError)
	from /home/oo/.gem/ruby/gems/classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:313:in `build_reduced_matrix'
	from /home/oo/.gem/ruby/gems/classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:143:in `build_index'
	from /home/oo/.gem/ruby/gems/classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:77:in `add_item'

**Comment by Ch4s3** [comment]
@texrg What does you input look like?

**Comment by cardmagic** [comment]
This is the same NaN numerical stability issue as #69. The original [classifier gem](https://github.com/cardmagic/classifier) has fixed this - see my comment there: https://github.com/jekyll/classifier-reborn/issues/69#issuecomment-3700133489

The fixes include proper handling of zero vectors in normalization and guarding against NaN propagation throughout the LSI calculations.
