### ISSUE TITLE
TypeError: no implicit conversion from nil to integer in /classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:313:in `sort'

### ISSUE THREAD

**Issue by stephenhmarsh** [jekyll/classifier-reborn#184]
```ruby
terms = %w(artist_name artist_years art_title signature_info medium dimensions dimensions art_created_year) 

lsi = ClassifierReborn::LSI.new

array = ["Jean Arp", "1886 - 1966", "FIGURE-GERME DITE \"L'APRÈS-MIDINETTE\"", "Stamped with the raised initials HA and numbered V/V (on the interior)", "Bronze", "Height: 32 in.", "81.3 cm", "Conceived in 1958-59; this example cast by Georges Rudier in 1964."]

array.each_with_index do |text, index|
  lsi.add_item(text, terms[index])
end
```

throws:

```ruby
TypeError: no implicit conversion from nil to integer
from /Users/stephen/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:313:in `sort'
```

trace:
```ruby
wtf?
Exception: TypeError: no implicit conversion from nil to integer
--
0: /Users/stephen/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:313:in `sort'
1: /Users/stephen/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:313:in `build_reduced_matrix'
2: /Users/stephen/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:143:in `build_index'
3: /Users/stephen/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/classifier-reborn-2.2.0/lib/classifier-reborn/lsi.rb:77:in `add_item'
4: (pry):130:in `block in __pry__'
5: (pry):129:in `each'
6: (pry):129:in `each_with_index'
7: (pry):129:in `__pry__'
8: /Users/stephen/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `eval'
9: /Users/stephen/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `evaluate_ruby'
```

object:
```ruby
lsi
=> #<ClassifierReborn::LSI:0x00007f98966163f0
 @auto_rebuild=true,
 @built_at_version=-1,
 @cache_node_vectors=nil,
 @items=
  {"Jean Arp"=>#<ClassifierReborn::ContentNode:0x00007f98953ad5b0 @categories=["artist_name"], @lsi_norm=nil, @lsi_vector=nil, @raw_norm=Vector[0.7071067811865475, 0.7071067811865475, 0.0, 0.0], @raw_vector=Vector[1.0, 1.0, 0.0, 0.0], @word_hash={:jean=>1, :arp=>1}>,
   "1886 - 1966"=>
    #<ClassifierReborn::ContentNode:0x00007f98953ad290 @categories=["artist_years"], @lsi_norm=nil, @lsi_vector=nil, @raw_norm=Vector[0.0, 0.0, 0.7071067811865475, 0.7071067811865475], @raw_vector=Vector[0.0, 0.0, 1.0, 1.0], @word_hash={:"1886"=>1, :"1966"=>1}>},
 @language="en",
 @version=2,
 @word_list=#<ClassifierReborn::WordList:0x00007f98953ad240 @location_table={:jean=>0, :arp=>1, :"1886"=>2, :"1966"=>3}>>
```

**Comment by Ch4s3** [comment]
@stephenhmarsh This is a bug that has existed since the original implementation that as resisted numerous attempts to fix it. I could be because you input is too short for lsi, but I'm not sure.

**Comment by cardmagic** [comment]
This TypeError issue appears to be related to the numerical stability problems in the SVD implementation. The original [classifier gem](https://github.com/cardmagic/classifier) has rewritten the SVD with better error handling:

1. **Proper handling of edge cases** where singular values become nil or NaN
2. **Zero vector normalization** returns zeros instead of propagating errors
3. **Native C extension option** for more robust linear algebra operations

See my detailed comment on #69: https://github.com/jekyll/classifier-reborn/issues/69#issuecomment-3700133489
