### ISSUE TITLE
Encoding::CompatibilityError for hasher

### ISSUE THREAD

**Issue by jcomello** [jekyll/classifier-reborn#49]
I'm using an older version of ruby (1.9.3) and I getting the following error. I notice that the hasher.rb file does not have the encoding specified. 
May I fix it and send a PR?

Thanks guys.
```
Encoding::CompatibilityError: incompatible encoding regexp match (ASCII-8BIT regexp with UTF-8 string)
/Users/joao/.rvm/gems/ruby-1.9.3-p551@admin-novo/bundler/gems/classifier-reborn-e832ae342ff5/lib/classifier-reborn/extensions/hasher.rb:23:in `gsub'
/Users/joao/.rvm/gems/ruby-1.9.3-p551@admin-novo/bundler/gems/classifier-reborn-e832ae342ff5/lib/classifier-reborn/extensions/hasher.rb:23:in `clean_word_hash'
/Users/joao/.rvm/gems/ruby-1.9.3-p551@admin-novo/bundler/gems/classifier-reborn-e832ae342ff5/lib/classifier-reborn/extensions/hasher.rb:16:in `word_hash'
/Users/joao/.rvm/gems/ruby-1.9.3-p551@admin-novo/bundler/gems/classifier-reborn-e832ae342ff5/lib/classifier-reborn/bayes.rb:50:in `train'
```

**Comment by Ch4s3** [comment]
Please feel free to send a PR. We'll probably drop 1.9.3 in future releases, but we can  incorporate small fixes like this in the meantime.

**Comment by parkr** [comment]
@jcomello can you see if adding the magic encoding header helps this? just add the following `hasher.rb`

```ruby
# encoding: UTF-8
```
