### ISSUE TITLE
NoMethodError: undefined method `+' for nil:NilClass at Train method

### ISSUE THREAD

**Issue by jcomello** [jekyll/classifier-reborn#55]
Hi, I'm getting this error for train method.

```
NoMethodError: undefined method `+' for nil:NilClass
/Users/my/directory/classifier-reborn/lib/classifier-reborn/bayes.rb:52:in `block in train'
/Users/my/directory/classifier-reborn/lib/classifier-reborn/bayes.rb:51:in `each'
/Users/my/directory/classifier-reborn/lib/classifier-reborn/bayes.rb:51:in `train'
```

The problem is in:

```ruby
def train(category, text)
  ...
  @category_counts[category] += 1
  Hasher.word_hash(text, @language).each do |word, count|
    @categories[category][word]      += count
    @category_word_count[category]   += count
    @total_words += count
  end
end
```
When, for example, @categories[category][word] is nil, it get this error. I solve it calling the to_i method.
It changed for
```ruby
def train(category, text)
  ...
  @category_counts[category] =   @category_counts[category].to_i + 1
  Hasher.word_hash(text, @language).each do |word, count|
    @categories[category][word]      = @categories[category][word].to_i + count
    @category_word_count[category]   = @category_word_count[category].to_i + count
    @total_words += count
  end
end
```

The thing is, I trying to reproduce this error in a test. Can you help me?

**Comment by Ch4s3** [comment]
same as #56
