### ISSUE TITLE
LSI is broken af.

### ISSUE THREAD

**Issue by henrebotha** [jekyll/classifier-reborn#69]
I'm on Ruby 2.2.4. I'm trying to use LSI. Nothing works, and the error messages SUCK. I've tried both the last release (i.e. the gem version) and the latest commit from Github.

```ruby
lsi = ClassifierReborn::LSI.new
training_data = ["Bcom", "Corporate Administration", "Forensic Auditing"]
category = :accounting
training_data.each do |d|
  begin
    lsi.add_item(d, category)
  rescue StandardError => e
    puts "#{d} misbehaving: #{e.message}"
  end
end

#=> Forensic Auditing misbehaving: comparison of Float with NaN failed
```

**Comment by Ch4s3** [comment]
There are some known issues with LSI. Are you using GNU GSL or the native Ruby version? If you're using the native ruby version, it relies on a buggy Ruby implementation of a matrix transform (discussed here #30)  and throws this type of error for some input. If that's the case, using GNU GSL will fix this. If you're using GNU GSL, this will require some digging.

**Comment by henrebotha** [comment]
You're fast! I am using the native Ruby version. I'll hit up GNU GSL and see what happens.

If I were you I'd mention this in the Readme.

**Comment by Ch4s3** [comment]
I happened to be on the issues. Yeah, let me know how GNU GSL works out. I need to rewrite the SVD, but I'm not a great C programmer so the process has been slow to say the least. If you're trying to train with small inputs especially ones that use abbreviations, the matrix transform is highly likely to break in the Ruby only version.

**Comment by henrebotha** [comment]
While I have you, I'm getting this:

```
GSL::ERROR::EUNIMPL: Ruby/GSL error code 24, svd of MxN matrix, M<N, is not implemented (file svd.c, line 61), the requested feature is not (yet) implemented
from /Users/leaply/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/bundler/gems/classifier-reborn-4e3bb14d6388/lib/classifier-reborn/lsi.rb:292:in `SV_decomp'
```

**Comment by Ch4s3** [comment]
Hum, could be related to this https://github.com/SciRuby/rb-gsl/issues/21. I'm investigating.

**Comment by Ch4s3** [comment]
Which version of GSL did you pull down?

**Comment by henrebotha** [comment]
1.16 via homebrew

**Comment by Ch4s3** [comment]
1.16 might work, let me try to pull down fresh versions later and try locally.

**Comment by Ch4s3** [comment]
I haven't gotten anywhere with this, cna anyone else reproduce this?

**Comment by Ch4s3** [comment]
@henrebotha can you try with the latest master to see if #77 raises an error on your input?

**Comment by henrebotha** [comment]
That's gonna take some doing. I'll try when I have access to a Mac.

**Comment by Ch4s3** [comment]
@henrebotha have you tried this yet?

**Comment by Ch4s3** [comment]
I intend to close this if there's no more action in the next few days.

**Comment by timcraft** [comment]
@Ch4s3 @henrebotha I'm seeing the same issue with my data and can reproduce with this script:

```ruby
require 'classifier-reborn'

lsi = ClassifierReborn::LSI.new

# Without gsl this raises NoMethodError
# /classifier-reborn-2.0.4/lib/classifier-reborn/lsi.rb:143:
# in `block in build_index': undefined method `normalize' for nil:NilClass

# With gsl this raises GSL::ERROR::EUNIMPL
# /classifier-reborn-2.0.4/lib/classifier-reborn/lsi.rb:292:in `SV_decomp':
# Ruby/GSL error code 24, svd of MxN matrix, M<N, is not implemented (file svd.c, line 60),
# the requested feature is not (yet) implemented

lsi.add_item 'England', 'xx'
lsi.add_item 'England & Wales', 'xx'
lsi.add_item 'England And Wales', 'xx'
```

Using GNU GSL, tried upgrading from 2.2.1 to 2.3 and that didn't fix it.

Related to [this TODO](https://github.com/jekyll/classifier-reborn/blob/master/lib/classifier-reborn/lsi.rb#L306) in lsi.rb?

**Comment by mepatterson** [comment]
Any ideas on this? I'm seeing the Ruby/GSL-derived exception in `SV_decomp` whenever I try to build an index on more than around 2,000 sentences. I have 4,007 sentences I'd like to index. For those 2000 the classifier works great for my purpose, so I'm really eager to find a way to get this working properly, if possible...

**Comment by Ch4s3** [comment]
@mepatterson I'd guess you have some malformed input. Can you throw a `begin rescue` around your training and see which doc/line blows it up?

@timcraft I know this sounds stupid, but have you double checked that you're actually using GNU GSL? It may not have loaded correctly.

**Comment by mepatterson** [comment]
Actually I can confirm @timcraft repro also. Just those three add item
lines will cause the gsl crash every time on my machine using very latest
gsl and rb-gsl

**Comment by Ch4s3** [comment]
Ok, I'll try to dig in this weekend.

**Comment by timcraft** [comment]
@Ch4s3 Yep, it appears to be loaded ok. I added this at the top of the script (matrix code from gsl-2.1.0.2/examples/linalg/SV.rb which uses SV_decomp):

```ruby
puts "Using GSL/#{GSL::VERSION} RubyGSL/#{GSL::RUBY_GSL_VERSION}"
a = GSL::Matrix[[3, 5, 2], [6, 2, 1], [4, 7, 3]]
u, v, s = a.SV_decomp
p u*GSL::Matrix.diagonal(s)*v.trans
```
Output is `Using GSL/2.3 RubyGSL/2.1.0.2`.

**Comment by elisaado** [comment]
Same here.

**Comment by Ch4s3** [comment]
@elisaado can you post any details?

**Comment by cardmagic** [comment]
FYI, the original [classifier gem](https://github.com/cardmagic/classifier) has addressed these numerical stability issues:

**1. Vector normalization handles zero vectors:**
```ruby
def normalize
  magnitude_value = magnitude
  return Vector[*Array.new(size, 0.0)] if magnitude_value <= 0.0  # Returns zeros instead of NaN
  # ...
end
```

**2. SVD handles negative floating point errors:**
```ruby
singular_values = q_rotation_matrix.row_size.times.map do |r|
  Math.sqrt([q_rotation_matrix[r, r].to_f, 0.0].max)  # Clamps to 0 before sqrt
end
```

**3. NaN values are skipped during accumulation:**
```ruby
weighted_total += val unless val.nan?
```

**4. EPSILON prevents division by zero:**
```ruby
divisor = sign * [weighted_total.abs, Vector::EPSILON].max
```

Additionally, the classifier gem now has an optional **native C extension** for linear algebra operations that provides 5-10x faster SVD with better numerical stability.

See: 
- https://github.com/cardmagic/classifier/blob/master/lib/classifier/extensions/vector.rb
- https://github.com/cardmagic/classifier/blob/master/lib/classifier/lsi/content_node.rb
