### ISSUE TITLE
Issue with sqrt

### ISSUE THREAD

**Issue by neo-apz** [jekyll/classifier-reborn#78]
When I execute Jekyll with LSI enabled (using `--lsi`) I run into an error:
```
Math::DomainError: Numerical argument is out of domain - "sqrt"
```

I believe the error occurs in [line 58](https://github.com/jekyll/classifier-reborn/blob/3488245735905187713823ea731fc353634d8763/lib/classifier-reborn/extensions/vector.rb#L58) of `vector.rb`. Apparently, the input number is negative and this causes the error. As also mentioned [here](http://stackoverflow.com/questions/18569027/how-to-compute-the-square-root-of-negative-numbers), this can be fixed by using `CMath.sqrt` instead of `Math.sqrt` to use complex numbers.

In my case, the issue shows up when I have duplicate posts (I had them because I was testing the pagination).

**Comment by Ch4s3** [comment]
Interesting in 2 years of this coming up, no one else has ever pointed out `CMath`! Amazing, I had no idea that it existed. This will throw an issue on duplicate documents and on sets of documents with 0 overlap.

Looks like this is the implementation of `CMath.sqrt`

```ruby
def sqrt(z)
  begin
    if z.real?
      if z < 0
        Complex(0, RealMath.sqrt(-z))
      else
        RealMath.sqrt(z)
      end
    else
      if z.imag < 0 ||
          (z.imag == 0 && z.imag.to_s[0] == '-')
        sqrt(z.conjugate).conjugate
      else
        r = z.abs
        x = z.real
        Complex(RealMath.sqrt((r + x) / 2.0), RealMath.sqrt((r - x) / 2.0))
      end
    end
  rescue NoMethodError
    handle_no_method_error
  end
end
```

It seems like this `Complex(0, RealMath.sqrt(-z))` deals with our negative. I'll make a change and we can double check the fix. If it works we can roll out a new minor version.

**Comment by Ch4s3** [comment]
I need to figure out some new tests to cover this, so I'll try to do it tonight.

**Comment by Ch4s3** [comment]
@neo-apz I'm going to try to roll this into the `2.0.5` release, hopefully this weekend.

**Comment by Ch4s3** [comment]
Does this capture your error?

```ruby
  def test_very_similar_texts
    dup = @str1
    lsi = ClassifierReborn::LSI.new
    lsi.add_item @str1, 'Dog'
    lsi.add_item dup, 'Dog'

    assert_equal 'Dog', lsi.classify(@str1)
    assert_equal 'Dog', lsi.classify(dup)
  end
```

```ruby
Error: test_very_similar_texts(LSITest):
  TypeError: can't convert NilClass into an Array (undefined method `to_ary' for nil:NilClass
  Did you mean?  to_a
                 to_r)
/Users/chase/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/matrix.rb:1552:in `rescue in convert_to_array'
/Users/chase/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/matrix.rb:1549:in `convert_to_array'
/Users/chase/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/matrix.rb:168:in `block in rows'
/Users/chase/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/matrix.rb:167:in `map!'
/Users/chase/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/matrix.rb:167:in `rows'
/Users/chase/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/matrix.rb:154:in `[]'
/Users/chase/code/classifier-reborn/lib/classifier-reborn/lsi.rb:190:in `block in proximity_array_for_content'
/Users/chase/code/classifier-reborn/lib/classifier-reborn/lsi.rb:186:in `collect'
/Users/chase/code/classifier-reborn/lib/classifier-reborn/lsi.rb:186:in `proximity_array_for_content'
/Users/chase/code/classifier-reborn/lib/classifier-reborn/lsi.rb:274:in `scored_categories'
/Users/chase/code/classifier-reborn/lib/classifier-reborn/lsi.rb:260:in `classify'
/Users/chase/code/classifier-reborn/test/lsi/lsi_test.rb:76:in `test_very_similar_texts'
     73:     lsi.add_item @str1, 'Dog'
     74:     lsi.add_item dup, 'Dog'
     75:
  => 76:     assert_equal 'Dog', lsi.classify(@str1)
     77:     assert_equal 'Dog', lsi.classify(dup)
     78:   end
     79:
```

**Comment by Ch4s3** [comment]
Check out my attempt to reproduce it here https://github.com/jekyll/classifier-reborn/compare/cmath?expand=1#diff-7ebb972757ff8fab036080df3fb0c63f

**Comment by Ch4s3** [comment]
@ibnesayeed are you able to reproduce this by any chance? I still can't trigger this issue.

**Comment by ibnesayeed** [comment]
@Ch4s3 I can reproduce the error you got in `test_very_similar_texts`, but can't really think of a way to make a test case to reproduce what OP has mentioned. Perhaps some more insights from @neo-apz about his environment and data would be helpful.

**Comment by Ch4s3** [comment]
@ibnesayeed thanks. wanted to make sure I wasn't missing something here.

**Comment by Ch4s3** [comment]
closing due to inactivity. @neo-apz feel free to ping me and I'll reopen this.
