### ISSUE TITLE
ArgumentError: invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by ibnesayeed** [jekyll/classifier-reborn#82]
When I am running the test, I am getting `invalid byte sequence in US-ASCII` error from the `Hasher` class.

```
$ ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]
$ ruby test/extensions/hasher_test.rb
Loaded suite test/extensions/hasher_test
Started
...E
===================================================================================================
Error: test_default_stopwords(HasherTest): ArgumentError: invalid byte sequence in US-ASCII
/usr/src/app/lib/classifier-reborn/extensions/hasher.rb:59:in `split'
/usr/src/app/lib/classifier-reborn/extensions/hasher.rb:59:in `block (2 levels) in <module:Hasher>'
/usr/src/app/lib/classifier-reborn/extensions/hasher.rb:57:in `each'
/usr/src/app/lib/classifier-reborn/extensions/hasher.rb:57:in `block in <module:Hasher>'
test/extensions/hasher_test.rb:26:in `[]'
test/extensions/hasher_test.rb:26:in `test_default_stopwords'
     23: 
     24:   def test_default_stopwords
     25:     assert_not_empty Hasher::STOPWORDS['en']
  => 26:     assert_not_empty Hasher::STOPWORDS['fr']
     27:     assert_empty Hasher::STOPWORDS['gibberish']
     28:   end
     29: 
===================================================================================================
..

Finished in 0.003000319 seconds.
---------------------------------------------------------------------------------------------------
6 tests, 6 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
83.3333% passed
---------------------------------------------------------------------------------------------------
1999.79 tests/s, 1999.79 assertions/s
```

When I try to interact with it from the IRB console:

```irb
$ irb
irb(main):001:0> load './lib/classifier-reborn/extensions/hasher.rb'
=> true
irb(main):002:0> ClassifierReborn::Hasher::STOPWORDS['en']
=> #<Set: {"a", "again", "all", "along", "are", "also", "an", "and", "as", "at", "but", "by", "came", "can", "cant", "couldnt", "did", "didn", "didnt", "do", "doesnt", "dont", "ever", "first", "from", "have", "her", "here", "him", "how", "i", "if", "in", "into", "is", "isnt", "it", "itll", "just", "last", "least", "like", "most", "my", "new", "no", "not", "now", "of", "on", "or", "should", "sinc", "so", "some", "th", "than", "this", "that", "the", "their", "then", "those", "to", "told", "too", "true", "try", "until", "url", "us", "were", "when", "whether", "while", "with", "within", "yes", "you", "youll"}>
irb(main):003:0> ClassifierReborn::Hasher::STOPWORDS['fr']
ArgumentError: invalid byte sequence in US-ASCII
	from /usr/src/app/lib/classifier-reborn/extensions/hasher.rb:59:in `split'
	from /usr/src/app/lib/classifier-reborn/extensions/hasher.rb:59:in `block (2 levels) in <module:Hasher>'
	from /usr/src/app/lib/classifier-reborn/extensions/hasher.rb:57:in `each'
	from /usr/src/app/lib/classifier-reborn/extensions/hasher.rb:57:in `block in <module:Hasher>'
	from (irb):3
	from /usr/local/bin/irb:11:in `<main>'
irb(main):004:0> 
```

**Comment by Ch4s3** [comment]
Very odd, that input should be read in as UTF-8, as we only support that encoding. I'm not sure what the issue is here.

**Comment by ibnesayeed** [comment]
Here are the complete steps to reproduce it (assuming that Docker is installed on the machine).

```
$ cd /tmp
$ git clone git@github.com:jekyll/classifier-reborn.git
$ docker run -it --rm -v "$PWD":/usr/src/app -w /usr/src/app ruby:2.3.3 bash
# bundle install
# ruby test/extensions/hasher_test.rb
```

I also tried using `rake` command to test all the cases, but to make it easier to point out where the issue is, I only illustrated the `hasher_test.rb` file. Running the whole test suit also produces a lot of warnings saying (which I think is not an issue):

```
warning: global variable `$GSL' not initialized
```
